[project]
name = "postman-api-testing-ecommerce"
version = "0.1.0"
description = ""
authors = [
    {name = "sheethal",email = "hmsheethal123@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.13,<4"
dependencies = [
    "schemathesis (>=4.20.0,<5.0.0)",
    "openai (>=2.38.0,<3.0.0)",
    "ollama (>=0.6.2,<0.7.0)",
    "requests (>=2.34.2,<3.0.0)",
    "dotenv (>=0.9.9,<0.10.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
